name: Flutter Web Deploy to GCP

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web

    - name: Deploy to GCP Instance
      env:
        SSH_KEY: ${{ secrets.MY_KEY }}
        GCP_IP: ${{ secrets.GCP_IP }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 600 key.pem
        scp -i key.pem -r build/web/* $USERNAME@$GCP_IP:/web
        ssh -i key.pem $USERNAME@$GCP_IP 'sudo systemctl restart nginx'
        rm key.pem
