name: Deploy Flutter Web Build to GCP VM

on:
  push:
    branches:
      - main  # Adjust this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Flutter environment
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.16.4" 

    # Step 3: Build the Flutter web project
    - name: Build Flutter web
      run: flutter build web --release

   # Step 4: Create .ssh directory if it doesn't exist and add VM's host key to known_hosts
    - name: Add VM to known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts


    # Step 4: Set up SSH authentication
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.MY_KEY }}

    # Step 5: Upload the web build to the VM
    - name: Upload build to VM
      run: |
        scp -r ./build/web/* ${{ secrets.USERNAME }}@${{ secrets.GCP_IP }}:/web
