name: Flutter Web Deploy to GCP

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.4'  
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web

    - name: Deploy to GCP Instance
      env:
        SSH_KEY: ${{ secrets.MY_KEY }}
        GCP_IP: ${{ secrets.GCP_IP }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        # Save the SSH key to a file and set permissions
        echo "$SSH_KEY" > key
        chmod 600 key

        # Disable strict host key checking and copy the web build files
        scp -o StrictHostKeyChecking=no -i key -r build/web/* $USERNAME@$GCP_IP:/web

        # Restart Nginx on the server
        ssh -o StrictHostKeyChecking=no -i key $USERNAME@$GCP_IP 'sudo systemctl restart nginx'

        # Remove the SSH key file for security
        rm key
