name: Flutter Web Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.4'
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web

    - name: Set up SSH key
      run: |
        # Ensure the .ssh directory exists
        mkdir -p ~/.ssh

        # Save the SSH key to a file and set permissions
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to GCP Instance
      env:
        GCP_IP: ${{ secrets.GCP_IP }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        # Disable strict host key checking and copy the web build files with verbose output
        scp -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r build/web/* $USERNAME@$GCP_IP:/web

        # Restart Nginx on the server with verbose output
        ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USERNAME@$GCP_IP 'sudo systemctl restart nginx'
